import { z } from "zod";

export const templateSchema = z.object({
	name: z.string(),
	description: z.string().optional(),
	isActive: z.boolean(),
	header: z.object({
		height: z.number(),
		color: z.string(),
		showLogo: z.boolean(),
		logoPath: z.string().nullable(),
		logoPositionX: z.number().optional(),
		logoPositionY: z.number().optional(),
		logoWidth: z.number().optional(),
		logoHeight: z.number().optional(),
		marginTop: z.number().optional(),
		marginLeft: z.number().optional(),
		marginRight: z.number().optional(),
	}),
	footer: z.object({
		height: z.number(),
		color: z.string(),
		pageNumberPosition: z.string(),
		email: z.string().optional(),
		address: z.string().optional(),
		marginTop: z.number().optional(),
		marginLeft: z.number().optional(),
		marginRight: z.number().optional(),
	}),
	font: z.object({
		titleFont: z.string(),
		titleSize: z.number(),
		textFont: z.string(),
		textSize: z.number(),
		lineHeight: z.number(),
		paragraphSpacing: z.number(),
	}),
	cover: z.object({
		photoPosition: z.string(),
		width: z.number(),
		height: z.number(),
		titleAlignment: z.string(),
		margin: z.number(),
	}),
	titleColors: z.object({
		h1Color: z.string(),
		h2Color: z.string(),
		h3Color: z.string(),
		h4Color: z.string(),
		h5Color: z.string(),
		h6Color: z.string(),
	}),
	finalPage: z.object({
		show: z.boolean(),
		text: z.string().optional(),
		backgroundColor: z.string(),
		textColor: z.string(),
		font: z.string(),
		fontSize: z.number(),
	}),
});
